from __future__ import annotations

from apihashing.plugin_api import FunctionHashImplementation


def fnv1a_32(data: bytes, seed: int) -> int:
    val = seed & 0xFFFFFFFF
    for c in data:
        val = (0x1000193 * (c ^ val)) & 0xffffffff
    return val


def _hash(library_name: str, symbol_name: str, params: dict[str, object]) -> int:
    del library_name
    # Use 'base' as the seed if provided, otherwise default to the standard FNV-1a seed
    seed_val = params.get('base', params.get('seed', 0x811c9dc5))
    if isinstance(seed_val, str):
        if seed_val.startswith('0x'):
            seed = int(seed_val, 16)
        else:
            seed = int(seed_val)
    else:
        seed = int(seed_val)
    return fnv1a_32(symbol_name.encode('utf-8'), seed)


# List of base values (seeds) found in sample d68ce82e82801cd487f9cd2d24f7b30e353cafd0704dcdf0bb8f12822d4227c2
KNOWN_SEEDS = [
    0x25BE6DAF,  # entry (pair 1)
    0x8E8A2795,  # entry (pair 2)
    0xC60BA40C,  # FUN_140001590
    0x4B0EB402,  # FUN_140001590
    0x5010FA78,  # FUN_140001590
    0x40EE5099,  # FUN_140001590
    0x47F09A35,  # FUN_140001590
    0xAF99254C,  # FUN_140001590
    0x05001E2D,  # FUN_140001590
    0x197A14DD,  # FUN_140001590
    0x663DBECA,  # FUN_140001590
    0xFAA1F95A,  # FUN_140001590
    0xA537705A,  # FUN_140001590
    0xA9AE4FF2,  # FUN_140001590
    0xB59B7792,  # FUN_140001590
    0xC9FEE8A2,  # FUN_140001590
    0xD974D0C6,  # FUN_140001590
    0xA6D9AD05,  # FUN_140001590
    0x3D517273,  # FUN_140001590
    0xA1814EB9,  # FUN_140001590
    0xBBF1952E,  # FUN_140001590
    0xFB21CE79,  # FUN_140001590
    0x67E2C383,  # FUN_140001590
    0x3A6DAE4C,  # FUN_140001590
    0x07C580CC,  # FUN_140001590
    0x289904AA,  # FUN_140001590
    0xF7FE3D8A,  # FUN_140001590
    0xE5A9DA2A,  # FUN_140001590
    0x52EA37C6,  # FUN_1400041a0
    0x3D01A2F2,  # FUN_140004900
    0x82EEED0F,  # FUN_140004900
    0x2557BAD7,  # FUN_140004900
    0x8E5CDD50,  # FUN_140004900
    0x0B4ED559,  # FUN_140004900
    0x9BB9C562,  # FUN_140004900
    0xEC7ED141,  # FUN_14000b710
    0xE76FBED8,  # FUN_14000b710
    0x074DEC1C,  # FUN_14000b710
    0x82DB73A8,  # FUN_140005470
    0x746D7EAE,  # FUN_140005470
    0x8292993C,  # FUN_140005470
    0xF0256776,  # FUN_140005470
    0xBA26ED68,  # FUN_140005470
    0x9BB8DF3E,  # FUN_140005470
    0x2D341E7E,  # FUN_140007ba0
    0x2D81A9C3,  # FUN_140007ba0
    0x38A20EBF,  # FUN_140007ba0
    0x3B9D94F9,  # FUN_140007ba0
    0xAC220035,  # FUN_14000bcb0
    0x2BC4FE14,  # FUN_14000bcb0
    0x98C7E842,  # FUN_14000bcb0
]

DESCRIPTION = f"""FNV-1a variant found in sample d68*. 
Uses variable seeds (base values). 
Known seeds include: {', '.join(hex(s) for s in KNOWN_SEEDS)}"""

HASH_IMPLEMENTATION = FunctionHashImplementation(
    id='d68_fnv1a',
    display_name='D68 FNV-1a',
    callback=_hash,
    description=DESCRIPTION,
    hash_size_bits=32,
    author='Generated by Gemini CLI',
    supports_base_values=True,
)
